### ISSUE TITLE
smogon_eval.py error

### ISSUE THREAD

**Issue by thomasundo2** [yuzeh/metagrok#1]
I'm having a few issues when running the following command: 

```
./rp metagrok/exe/smogon_eval.py \
    metagrok.pkmn.models.v3_capacity.QuadCapacity:static/sample-v3-quad-model.pytorch \
    --num-matches 8 \
    --max-concurrent 4 \
    --host localhost --port 8000
```
I attempted to run it standalone and also with node pokemon-showdown, but I get this error: 

```
2019-07-12 00:29:31,379 ~ root ~ INFO     ~ Setting up clothes-wardman on localhost:8000
2019-07-12 00:29:31,380 ~ root ~ INFO     ~ Outputting logs to data/evals/1562891371
2019-07-12 00:29:31,382 ~ Client(clothes-wardman) ~ DEBUG    ~ < |/autojoin
2019-07-12 00:29:31,395 ~ <metagrok.showdown.connection.ShowdownConnection object at 0x7f69f962da20> ~ ERROR    ~ Fuck this shit, I am outta here
Traceback (most recent call last):
  File "/root/workspace/metagrok/showdown/actor.py", line 135, in _run
    actor.on_start()
  File "/root/workspace/metagrok/showdown/connection.py", line 25, in on_start
    self._s.ws = websocket.create_connection(self._url, timeout = TIMEOUT_SECONDS)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/websocket/_http.py", line 189, in _open_socket
    raise error
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/websocket/_http.py", line 172, in _open_socket
    sock.connect(address)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/gevent/_socket3.py", line 356, in connect
    raise error(result, strerror(result))
OSError: [Errno 99] Cannot assign requested address
```

It seems as if the localhost is not compiling correctly. head2head.py works fine, so I don't think it's an issue with the client. I also tried to set the host as sim.smogon.com, but the following error also occurs.

```
2019-07-12 00:34:17,793 ~ root ~ INFO     ~ Setting up best-bezanty on sim.smogon.com:8000
2019-07-12 00:34:17,794 ~ root ~ INFO     ~ Outputting logs to data/evals/1562891657
2019-07-12 00:34:17,795 ~ Client(best-bezanty) ~ DEBUG    ~ < |/autojoin
2019-07-12 00:34:17,860 ~ Client(best-bezanty) ~ DEBUG    ~ > |updateuser| Guest 4766090|0|2|{"isSysop":false,"isStaff":false,"blockChallenges":false,"blockPMs":false,"ignoreTickets":false,"lastConnected":0,"inviteOnlyNextBattle":false}
2019-07-12 00:34:17,861 ~ Client(best-bezanty) ~ DEBUG    ~ > |formats|,1|US/UM Singles|[Gen 7] Random Battle,f|[Gen 7] Unrated Random Battle,b|[Gen 7] OU,e|[Gen 7] Ubers,e|[Gen 7] UU,e|[Gen 7] RU,e|[Gen 7] NU,e|[Gen 7] PU,e|[Gen 7] LC,e|[Gen 7] LC UU,c|[Gen 7] Monotype,e|[Gen 7] Anything Goes,e|[Gen 7] 1v1,e|[Gen 7] ZU,e|[Gen 7] CAP,e|[Gen 7] CAP LC,c|[Gen 7] Battle Spot Singles,1e|[Gen 7] Battle Spot Special 16,1e|[Gen 7] Custom Game,c|,1|US/UM Doubles|[Gen 7] Random Doubles Battle,f|[Gen 7] Doubles OU,e|[Gen 7] Doubles Ubers,e|[Gen 7] Doubles UU,e|[Gen 7] VGC 2019 Sun Series,1c|[Gen 7] VGC 2019 Moon Series,1c|[Gen 7] VGC 2019 Ultra Series,1e|[Gen 7] VGC 2018,1e|[Gen 7] VGC 2017,1c|[Gen 7] Battle Spot Doubles,1e|[Gen 7] 2v2 Doubles,c|[Gen 7] Metronome Battle,e|[Gen 7] Doubles Custom Game,c|,2|OM of the Month|[Gen 7] Nature Swap,e|[Gen 7] Follow the Leader,e|,2|Other Metagames|[Gen 7] Balanced Hackmons,e|[Gen 7] Mix and Mega,e|[Gen 7] Almost Any Ability,e|[Gen 7] Camomons,e|[Gen 7] STABmons,c|[Gen 7] Tier Shift,c|[Gen 7] Partners in Crime,e|[Gen 6] Gen-NEXT OU,8|,2|Let's Go!|[Gen 7 Let's Go] Random Battle,f|[Gen 7 Let's Go] OU,1e|[Gen 7 Let's Go] Singles No Restrictions,c|[Gen 7 Let's Go] Custom Game,c|[Gen 7 Let's Go] Doubles OU,1e|[Gen 7 Let's Go] Doubles No Restrictions,c|,2|Randomized Metas|[Gen 7] Battle Factory,f|[Gen 7] BSS Factory,f|[Gen 7] Monotype Random Battle,f|[Gen 7] Super Staff Bros Brawl,f|[Gen 7] Challenge Cup 1v1,f|[Gen 7] Challenge Cup 2v2,d|[Gen 7] Hackmons Cup,f|[Gen 7] Doubles Hackmons Cup,d|[Gen 6] Random Battle,f|[Gen 6] Battle Factory,d|[Gen 5] Random Battle,f|[Gen 4] Random Battle,f|[Gen 3] Random Battle,f|[Gen 2] Random Battle,f|[Gen 1] Random Battle,f|[Gen 1] Challenge Cup,9|,3|RoA Spotlight|[Gen 2] Ubers,e|[Gen 3] OU + Latias,e|[Gen 1] No big 4 OU,e|,3|Past Gens OU|[Gen 6] OU,e|[Gen 5] OU,e|[Gen 4] OU,e|[Gen 3] OU,e|[Gen 2] OU,e|[Gen 1] OU,e|,3|OR/AS Singles|[Gen 6] Ubers,c|[Gen 6] UU,c|[Gen 6] RU,c|[Gen 6] NU,c|[Gen 6] PU,c|[Gen 6] LC,c|[Gen 6] Monotype,c|[Gen 6] Anything Goes,c|[Gen 6] 1v1,c|[Gen 6] CAP,c|[Gen 6] Battle Spot Singles,1c|[Gen 6] Custom Game,c|,3|OR/AS Doubles/Triples|[Gen 6] Doubles OU,c|[Gen 6] VGC 2016,1c|[Gen 6] Battle Spot Doubles,1c|[Gen 6] Doubles Custom Game,c|[Gen 6] Battle Spot Triples,1c|[Gen 6] Triples Custom Game,c|,4|B2/W2 Singles|[Gen 5] Ubers,c|[Gen 5] UU,c|[Gen 5] RU,c|[Gen 5] NU,c|[Gen 5] LC,c|[Gen 5] Monotype,c|[Gen 5] 1v1,c|[Gen 5] GBU Singles,1c|[Gen 5] Custom Game,c|,4|B2/W2 Doubles|[Gen 5] Doubles OU,c|[Gen 5] GBU Doubles,1c|[Gen 5] Doubles Custom Game,c|,4|DPP Singles|[Gen 4] Ubers,c|[Gen 4] UU,c|[Gen 4] NU,c|[Gen 4] LC,c|[Gen 4] Anything Goes,c|[Gen 4] Custom Game,c|,4|DPP Doubles|[Gen 4] Doubles OU,c|[Gen 4] Doubles Custom Game,c|,4|Past Generations|[Gen 3] Ubers,c|[Gen 3] UU,c|[Gen 3] NU,c|[Gen 3] Custom Game,c|[Gen 3] Doubles Custom Game,c|[Gen 2] UU,c|[Gen 2] NU,c|[Gen 2] Custom Game,c|[Gen 1] Ubers,c|[Gen 1] UU,c|[Gen 1] OU (tradeback),c|[Gen 1] Stadium OU,c|[Gen 1] Custom Game,c
2019-07-12 00:34:17,863 ~ Client(best-bezanty) ~ ERROR    ~ did not attempt auth but was assigned username [ Guest 4766090]
2019-07-12 00:34:17,864 ~ Client(best-bezanty) ~ ERROR    ~ Fuck this shit, I am outta here
Traceback (most recent call last):
  File "/root/workspace/metagrok/showdown/actor.py", line 143, in _run
    actor.receive(message)
  File "/root/workspace/metagrok/showdown/client.py", line 70, in receive
    self._handle_ps_message(msg.data)
  File "/root/workspace/metagrok/showdown/client.py", line 190, in _handle_ps_message
    self._handle_auth_message(message)
  File "/root/workspace/metagrok/showdown/client.py", line 212, in _handle_auth_message
    self.die('did not attempt auth but was assigned username [%s]', username)
  File "/root/workspace/metagrok/showdown/actor.py", line 116, in die
    sys.exit(1)
```

Any advice would be greatly appreciated, thanks!

**Comment by yuzeh** [comment]
Hey! You've uncovered several issues here...

1. If you're running this in a Docker container and Showdown outside of the container, this will unfortunately fail. The command you should run instead:

```
./rp metagrok/exe/smogon_eval.py \
    metagrok.pkmn.models.v3_capacity.QuadCapacity:static/sample-v3-quad-model.pytorch \
    --num-matches 8 \
    --max-concurrent 4 \
    --host host.docker.internal --port 8000
```

I've gone ahead and fixed the README to reflect this.

2. There are no problems running head2head because head2head does not try to connect to a Showdown server. It runs `./pokemon-showdown simulate-battle` and feeds data into that process.

3. The issue with connecting to sim.smogon.com leads me to believe the server's behavior has changed slightly. I've done a git bisect and it seems like the offending commit is Zarel/Pokemon-Showdown@ed5d534224d52ea369514c19b1c7bd1d04d7551f . I'll take a look at this tomorrow and see if there's an obvious fix.

**Comment by yuzeh** [comment]
I took a quick look and it turns out the fix is pretty easy.

Let me know if it works now!

**Comment by thomasundo2** [comment]
Hi yuzeh, thanks for the fast response! So your advice for connecting the Docker container to the outside localhost worked; the 'Guest x' successfully connects to the server. It should be noted that in this instance, the line of code 
`username = username[1:]`
doesn't work; it'll become 'uest 1' for example. The obvious fix is to just make this line 
`username = username.strip() `

However, I was getting the following errors: 

```
2019-07-13 00:30:02,765 ~ Client(ananite-codder) ~ DEBUG    ~ > |challstr|4|a2838bf03b90edfcc7805f3c4c440dfd6f874f84f3bc90524a68ba544d3cb501ccf25a406fd05977af40d5174d2c392c5f7637b69073e6b13438ec415b865e01bb3da652af50aee6054076dd358b69f0de48c43a394712dd210c6dd1b710a49f224da5efb90b46651f5956e5ed0c8cfb1b741c37cfaeb187bd8d9499699317ac
2019-07-13 00:30:22,815 ~ Client(ananite-codder) ~ ERROR    ~ Fuck this shit, I am outta here
Traceback (most recent call last):
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/gevent/_socketcommon.py", line 208, in getaddrinfo
    return get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/gevent/resolver/thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 381, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 409, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 399, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 379, in gevent._event.AsyncResult._raise_exception
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/gevent/threadpool.py", line 281, in _worker
    value = func(*args, **kwargs)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/envs/metagrok/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/envs/metagrok/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/envs/metagrok/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/envs/metagrok/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/envs/metagrok/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fcb4af15320>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='play.pokemonshowdown.com', port=80): Max retries exceeded with url: /action.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb4af15320>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/workspace/metagrok/showdown/actor.py", line 143, in _run
    actor.receive(message)
  File "/root/workspace/metagrok/showdown/client.py", line 68, in receive
    self._handle_ps_message(msg.data)
  File "/root/workspace/metagrok/showdown/client.py", line 188, in _handle_ps_message
    self._handle_auth_message(message)
  File "/root/workspace/metagrok/showdown/client.py", line 198, in _handle_auth_message
    assertion = _fetch_assertion_string(username, challstr)
  File "/root/workspace/metagrok/showdown/client.py", line 242, in _fetch_assertion_string
    data = dict(act = 'getassertion', userid = username, challstr = challstr),
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='play.pokemonshowdown.com', port=80): Max retries exceeded with url: /action.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb4af15320>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```
I was able to fix this by hosting the server on a my phone's mobile hotspot, and then hosting it back on my wifi. Not sure what happened here. The sim.smogon.com works though, thanks for all the help!

**Comment by yuzeh** [comment]
The change I made only works for connecting to Showdown server versions after Zarel/Pokemon-Showdown@ed5d534... this might be why you are still seeing that error.

**Comment by ericrosenbrown** [comment]
Thank you so much @yuzeh for this project! It's awesome!

I'm currently on the most updated master branch of Pokemon-Showdown, and am also running the server outside the docker container. I'm able to connect to the localhost in browser with the server, but the smogon_eval.py has a similar issue for me with @thomasundo2 in terms of not being able to connect to the localhost outside the container. But I am able to connect to sim.smogon.com with smogon_eval.py to run the model!

For debuging now, I create a Pokemon Showndown server on a different computer on the same network, and I'm able to connect to that. I'm not sure why the localhost is failing though, it may be a docker issue? 


My error is the following:

Running: PYTHONPATH=${PYTHONPATH}:. python "metagrok/exe/smogon_eval.py" "metagrok.pkmn.models.v3_capacity.QuadCapacity:static/sample-v3-quad-model.pytorch" "--num-matches" "8" "--max-concurrent" "4" "--host" "host.docker.internal" "--port" "8000"
/usr/local/envs/metagrok/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:86: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
2019-08-06 06:09:58,490 ~ root ~ INFO     ~ Setting up lactary-elegy on host.docker.internal:8000
2019-08-06 06:09:58,491 ~ root ~ INFO     ~ Outputting logs to data/evals/1565071798
2019-08-06 06:09:58,491 ~ Client(lactary-elegy) ~ DEBUG    ~ < |/autojoin
2019-08-06 06:09:58,523 ~ <metagrok.showdown.connection.ShowdownConnection object at 0x7f3ae65642b0> ~ ERROR    ~ Fuck this shit, I am outta here
Traceback (most recent call last):
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/websocket/_http.py", line 143, in _get_addrinfo_list
    hostname, port, 0, 0, socket.SOL_TCP)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/gevent/_socketcommon.py", line 208, in getaddrinfo
    return get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/gevent/resolver/thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 381, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 409, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 399, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 379, in gevent._event.AsyncResult._raise_exception
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/gevent/threadpool.py", line 281, in _worker
    value = func(*args, **kwargs)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/workspace/metagrok/showdown/actor.py", line 135, in _run
    actor.on_start()
  File "/root/workspace/metagrok/showdown/connection.py", line 25, in on_start
    self._s.ws = websocket.create_connection(self._url, timeout = TIMEOUT_SECONDS)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/websocket/_http.py", line 113, in connect
    hostname, port, is_secure, proxy)
  File "/usr/local/envs/metagrok/lib/python3.7/site-packages/websocket/_http.py", line 154, in _get_addrinfo_list
    raise WebSocketAddressException(e)
websocket._exceptions.WebSocketAddressException: [Errno -2] Name or service not known

**Comment by yuzeh** [comment]
@ericrosenbrown my best guess is that the Docker guest's "DNS name" for its host machine is incorrect.

On the version that I'm running on (Docker Desktop Community for Mac, 2.0.0.3, Docker Engine 18.09.2), `host.docker.internal` seems to work. I'd recommend trying to interactively figure out how to access the host from inside the container. My knowledge of networking tools isn't strong but one really dumb way to do this is to try to use cURL to access a web server running on the container's host machine.
